[workspace]
members = ["client", "proc-macros", "server", "util"]

[workspace.dependencies]
bevy = { version = "0.11.3", features = ["dynamic_linking"] }
bevy-inspector-egui = "0.20.0"
bincode = "1.3.3"
proc-macros = { path = "./proc-macros" }
quote = "1.0.33"
serde = "1.0.189"
syn = "2.0.38"
util = { path = "./util" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
