[workspace]
members = ["client", "net", "server", "util"]

[workspace.dependencies]
bevy = "0.12"
bevy-inspector-egui = "0.21.0"
bincode = "1.3.3"
net = { path = "./net" }
quote = "1.0.33"
serde = { version = "1.0.190", features = ["derive"] }
syn = "2.0.38"
util = { path = "./util" }
websocket = "0.27.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
