[workspace]
members = ["client", "net", "server"]

[workspace.dependencies]
bevy = "0.11"
bevy-inspector-egui = "0.19"
net = { path = "./net" }
serde = "1.0.188"
bincode = "1.3.3"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
