[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy-inspector-egui = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }
util = { workspace = true }
