[package]
name = "util"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bincode = { workspace = true }
proc-macros = { workspace = true }
quote = { workspace = true }
serde = { workspace = true }
syn = { workspace = true }
